#!/bin/bash

fileName="assets/annotation/caption.ass"
argsc="$#"

# exit codes
success=0
invalidParameters=1
unknownCommand=2


if [ $argsc = "4" ] ;  
    then

    append=$1
    startTime=$2
    endTime=$3
    annotation=$4

    if [ $append = "-a" ] ;
        then
        echo -n "Dialogue: 0," >> $fileName
        echo -n $startTime >> $fileName
        echo -n "," >> $fileName
        echo -n $endTime >> $fileName
        echo -n ",Default,,0000,0000,0000,," >> $fileName
        echo -n $annotation >> $fileName

        echo "Values appended"
        exit $success
    fi

elif [ $argsc = "0" ] ;
    then

        echo "[Script Info]" > $fileName
        echo "; Script generated by Aegisub 2.1.8" >> $fileName
        echo "; http://www.aegisub.org/" >> $fileName
        echo "Title: Default Aegisub file" >> $fileName
        echo "ScriptType: v4.00+" >> $fileName
        echo "WrapStyle: 0" >> $fileName
        echo "PlayResX: 640" >> $fileName
        echo "PlayResY: 480" >> $fileName
        echo "ScaledBorderAndShadow: yes" >> $fileName
        echo "Video Aspect Ratio: 0" >> $fileName
        echo "Video Zoom: 6" >> $fileName
        echo "Video Position: 0" >> $fileName
        echo "Last Style Storage: Default" >> $fileName
        echo "[V4+ Styles]" >> $fileName
        echo "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding" >> $fileName
        echo "Style: Default,Arial,25,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,10,1" >> $fileName
        echo "[Events]" >> $fileName
        echo "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text" >> $fileName

        echo "New file created"
        exit $success
else

    echo "Unknown Command"
    exit $unknownCommand
fi














